Repository Evdigi-INA/generator, pull requests merged in 2024-10, with the labels that each got.

#54 Add Export Excel (beta)
  resources/views/include/api-form.blade.php
  resources/views/include/form.blade.php
  resources/views/simple-create.blade.php
  src/Generators/ControllerGenerator.php
  src/Generators/ExportExcelGenerator.php
  src/Generators/RouteGenerator.php
  src/Generators/Services/GeneratorService.php
  src/Generators/Views/IndexViewGenerator.php
  src/Http/Controllers/GeneratorController.php
  src/Http/Requests/StoreGeneratorRequest.php
  stubs/generators/controllers/controller.stub
  stubs/generators/controllers/export-function.stub
  stubs/generators/export.stub
  stubs/generators/views/export-button.stub
  stubs/generators/views/index.stub
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#57 Change str_replace with custom function
  src/Commands/SetSidebarType.php
  src/Generators/ControllerGenerator.php
  src/Generators/ExportExcelGenerator.php
  src/Generators/FactoryGenerator.php
  src/Generators/GeneratorUtils.php
  src/Generators/MigrationGenerator.php
  src/Generators/ModelGenerator.php
  src/Generators/RequestGenerator.php
  src/Generators/ResourceApiGenerator.php
  src/Generators/SeederGenerator.php
  src/Generators/Services/GeneratorService.php
  src/Generators/ViewComposerGenerator.php
  src/Generators/Views/ActionViewGenerator.php
  src/Generators/Views/CreateViewGenerator.php
  src/Generators/Views/EditViewGenerator.php
  src/Generators/Views/FormViewGenerator.php
  src/Generators/Views/IndexViewGenerator.php
  src/Generators/Views/ShowViewGenerator.php
Labels: hacktoberfest, hacktoberfest-accepted

#60 fix: error sentence
  src/Http/Requests/StoreGeneratorRequest.php
  src/Http/Requests/StoreSimpleGeneratorRequest.php
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#62 Fix unhandled match case '0'
  src/Generators/ControllerGenerator.php
  src/Generators/MigrationGenerator.php
  src/Generators/PermissionGenerator.php
  src/Generators/Services/GeneratorService.php
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#64 Make intervention image to optional dependency :sunflower:
  composer.json
  stubs/generators/publish/utils/Services/ImageService.php
Labels: enhancement, dependencies, hacktoberfest, hacktoberfest-accepted
